version: "3.8"
services:
    discovery-server:
        build: ./Discovery-Server
        container_name: discovery-server
        ports: 
          - target: 4494
            published: 4494
    artemis:
      build: ./Artemis
      container_name: artemis
      ports:
        - target: 61616
          published: 61616
          protocol: tcp
        - target: 8161
          published: 8161
          protocol: tcp
      volumes: 
        - type: bind
          source: ./jolokia-access.xml
          target: /artemis/mybroker/etc/jolokia-access.xml
    number-gen:
        build: ./Account-Num-Gen
        container_name: number-gen
        ports: 
          - target: 8082
            published: 8082
        depends_on:
          - "discovery-server"
    prize-gen:
        build: ./Account-Prize-Gen
        container_name: prize-gen
        ports: 
          - target: 8083
            published: 8083
        depends_on:
          - "discovery-server"
    account-api:
        build: ./Account-API
        container_name: account-api
        ports: 
          - target: 8081
            published: 8081
        depends_on:
          - "number-gen"
          - "prize-gen"
          - "artemis"
    jms-example:
        build: ./JMS-Example
        container_name: jms-example
        ports: 
          - target: 8181
            published: 8181
        depends_on:
          - "artemis"