version: "3.8"
services:
    discovery-server:
        build: ./Discovery-Server
        container_name: discovery-server
        ports: 
          - target: 4494
            published: 4494
    account-api:
        build: ./Account-API
        container_name: account-api
        ports: 
          - target: 8081
            published: 8081
        depends_on:
          - "discovery-server"
    number-gen:
        build: ./Account-Num-Gen
        container_name: number-gen
        ports: 
          - target: 8082
            published: 8082
        depends_on:
          - "account-api"
    prize-gen:
        build: ./Account-Prize-Gen
        container_name: prize-gen
        ports: 
          - target: 8083
            published: 8083
        depends_on:
          - "account-api"